### ISSUE TITLE
Fix Grid 

### ISSUE THREAD

**Issue by palewire** [palewire/news-homepages#234]
## Screenshot
![gridnews](https://user-images.githubusercontent.com/9993/183310582-a02b40d2-6881-4b7e-a8f7-f7f442862ecc.jpg)

A solution is often found by adding JavaScript or CSS via a site-specific include, [as covered in our documentation](https://palewi.re/docs/news-homepages/adding.html#hide-ads-and-popups).

**Comment by AsaiToshiya** [comment]
Probably this issue has been fixed in fb65ad0.

**Comment by palewire** [comment]
Something isn't working, because the popup is still appearing in some but not all screenshots. https://palewi.re/docs/news-homepages/sites/gridnews.html

**Comment by AsaiToshiya** [comment]
Maybe timing problem when a modal to appear.
